### ISSUE TITLE
Jakiś error przy zabiciu

### ISSUE THREAD

**Issue by kukubaczek** [EastWestFM/RevoGuild#11]
TAKI ERROR WSYKAKUJE GDY ZABIJE STIFKA:
[18:31:05 ERROR]: Could not pass event PlayerDeathEvent to RevoGuild v0.2.0-b187
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-1608]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-1608]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [craftbukkit.jar:git-Spigot-1608]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [craftbukkit.jar:git-Spigot-1608]
    at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:396) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.EntityPlayer.die(EntityPlayer.java:385) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.EntityLiving.damageEntity(EntityLiving.java:745) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.EntityHuman.damageEntity(EntityHuman.java:763) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.EntityPlayer.damageEntity(EntityPlayer.java:464) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.EntityHuman.attack(EntityHuman.java:948) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1191) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.a(SourceFile:55) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.PacketPlayInUseEntity.handle(SourceFile:10) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1608]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1608]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double
    at net.karolek.revoguild.listeners.DeathListener.onDeath(DeathListener.java:56) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit.jar:git-Spigot-1608]
    ... 19 more

**Comment by EastWestFM** [comment]
zrobię fixa w nastepnej wersji ;3

**Comment by EastWestFM** [comment]
Poprawione ;)
