### ISSUE TITLE
Bład

### ISSUE THREAD

**Issue by ghost** [EastWestFM/RevoGuild#12]
[09:26:04] [Server thread/INFO]: [RevoGuild] Enabling RevoGuild v0.3.1-b239
[09:26:05] [Server thread/ERROR]: [RevoGuild] 
[09:26:05] [Server thread/ERROR]: [RevoGuild] An error occurred while running the plugin
[09:26:05] [Server thread/ERROR]: [RevoGuild] 
[09:26:05] [Server thread/ERROR]: [RevoGuild] Version Information:
[09:26:05] [Server thread/ERROR]: [RevoGuild]   RevoGuild: 0.3.1-b239
[09:26:05] [Server thread/ERROR]: [RevoGuild]   Bukkit: 1.7.9-R0.2
[09:26:05] [Server thread/ERROR]: [RevoGuild]   Java: 1.7.0_07
[09:26:05] [Server thread/ERROR]: [RevoGuild]   Thread: Thread[Server thread,5,main]
[09:26:05] [Server thread/ERROR]: [RevoGuild]   Running CraftBukkit: false
[09:26:05] [Server thread/ERROR]: [RevoGuild] 
[09:26:05] [Server thread/ERROR]: [RevoGuild] Stack trace: 
[09:26:05] [Server thread/ERROR]: [RevoGuild] Caused by: Can not set static boolean field net.karolek.revoguild.data.Config.TREASURE_ENABLED to java.lang.String
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:164)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:168)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at sun.reflect.UnsafeStaticBooleanFieldAccessorImpl.set(UnsafeStaticBooleanFieldAccessorImpl.java:84)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at java.lang.reflect.Field.set(Field.java:680)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at net.karolek.revoguild.data.Config.loadConfig(Config.java:112)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at net.karolek.revoguild.data.Config.reloadConfig(Config.java:135)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at net.karolek.revoguild.GuildPlugin.onEnable(GuildPlugin.java:64)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:446)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:380)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:352)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:326)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:282)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:182)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436)
[09:26:05] [Server thread/ERROR]: [RevoGuild]     at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628)
[09:26:05] [Server thread/ERROR]: [RevoGuild] 
[09:26:05] [Server thread/ERROR]: [RevoGuild] End of Error.
[09:26:05] [Server thread/ERROR]: [RevoGuild] 
[09:26:05] [Server thread/ERROR]: Cannot load plugins/RevoGuild/tablist.yml
org.bukkit.configuration.InvalidConfigurationException: unacceptable character '?' (0xFFFD) special characters are not allowed
in "<string>", position 300
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:226) ~[CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:169) ~[CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:180) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.karolek.revoguild.data.TabScheme.loadTablist(TabScheme.java:35) [RevoGuild.v0.3.1-b239.jar:?]
    at net.karolek.revoguild.data.TabScheme.reloadTablist(TabScheme.java:55) [RevoGuild.v0.3.1-b239.jar:?]
    at net.karolek.revoguild.GuildPlugin.onEnable(GuildPlugin.java:66) [RevoGuild.v0.3.1-b239.jar:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:446) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:380) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:352) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:326) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:282) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:182) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
Caused by: org.yaml.snakeyaml.reader.ReaderException: special characters are not allowed
    at org.yaml.snakeyaml.reader.StreamReader.checkPrintable(StreamReader.java:70) ~[CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:50) ~[CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.yaml.snakeyaml.Yaml.load(Yaml.java:399) ~[CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    ... 17 more
[09:26:05] [Server thread/ERROR]: Error occurred while enabling RevoGuild v0.3.1-b239 (Is it up to date?)
java.lang.NullPointerException
    at net.karolek.revoguild.data.TabScheme.loadTablist(TabScheme.java:37) ~[?:?]
    at net.karolek.revoguild.data.TabScheme.reloadTablist(TabScheme.java:55) ~[?:?]
    at net.karolek.revoguild.GuildPlugin.onEnable(GuildPlugin.java:66) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:324) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.loadPlugin(CraftServer.java:446) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.craftbukkit.v1_7_R3.CraftServer.enablePlugins(CraftServer.java:380) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.n(MinecraftServer.java:352) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.g(MinecraftServer.java:326) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.a(MinecraftServer.java:282) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.DedicatedServer.init(DedicatedServer.java:182) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:436) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [CBO.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]

**Comment by EastWestFM** [comment]
Wygeneruj na nowo config i tablist, bo zepsułeś :dancer:
