### ISSUE TITLE
EROR

### ISSUE THREAD

**Issue by kukubaczek** [EastWestFM/RevoGuild#13]
[13:36:08 INFO]: aruturek: Reload complete.
[13:36:08 WARN]: [RevoGuild] Can not find valid TagAPI instance!
[13:36:08 WARN]: [RevoGuild] Using ScoreBoard nametags!
[13:36:08 INFO]: [RevoGuild] Using 'ScoreBoard' to support nametags!
[13:36:10 INFO]: aruturek lost connection: Disconnected
[13:36:10 INFO]: aruturek left the game
[13:36:11 INFO]: UUID of player aruturek is 8155180e-0954-322e-8737-436b517bc08c
[13:36:11 ERROR]: Could not pass event PlayerJoinEvent to RevoGuild v0.3.1-b239
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PlayerList.c(PlayerList.java:265) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.PlayerList.a(PlayerList.java:152) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.LoginListener.c(LoginListener.java:119) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.LoginListener.a(LoginListener.java:44) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:189) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.ExceptionInInitializerError
    at net.karolek.revoguild.tablist.Tab.firstClear(Tab.java:76) ~[?:?]
    at net.karolek.revoguild.tablist.Tab.<init>(Tab.java:24) ~[?:?]
    at net.karolek.revoguild.managers.TabManager.createTab(TabManager.java:29) ~[?:?]
    at net.karolek.revoguild.listeners.JoinQuitListener.onJoin(JoinQuitListener.java:34) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    ... 14 more
Caused by: java.lang.IllegalStateException: Unable to find constructor for class net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo ([class java.lang.String, boolean, int]).
    at net.karolek.revoguild.utils.Reflection.getConstructor(Reflection.java:191) ~[?:?]
    at net.karolek.revoguild.tablist.TabUtil.<clinit>(TabUtil.java:15) ~[?:?]
    at net.karolek.revoguild.tablist.Tab.firstClear(Tab.java:76) ~[?:?]
    at net.karolek.revoguild.tablist.Tab.<init>(Tab.java:24) ~[?:?]
    at net.karolek.revoguild.managers.TabManager.createTab(TabManager.java:29) ~[?:?]
    at net.karolek.revoguild.listeners.JoinQuitListener.onJoin(JoinQuitListener.java:34) ~[?:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_05]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_05]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_05]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_05]
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
    ... 14 more
[13:36:11 INFO]: aruturek[/127.0.0.1:55591] logged in with entity id 2148 at ([world] -4.34174756975384, 61.0, 599.5324089394269)

**Comment by EastWestFM** [comment]
Spigot powyżej builda 1628?

**Comment by kukubaczek** [comment]
Tak
2 lis 2014 19:52 "EastWestFM" notifications@github.com napisał(a):

**Comment by EastWestFM** [comment]
To nie zadziała, tam się całkowicie zmienił pakiet od taba c:
