### ISSUE TITLE
Nie działą

### ISSUE THREAD

**Issue by ghost** [EastWestFM/RevoGuild#7]
Nie dziala TabLista :/

[19:26:45] [Server thread/WARN]: [RevoGuild] Task #14 for RevoGuild v0.2.0-b186 generated an exception
java.lang.ExceptionInInitializerError
    at net.karolek.revoguild.tablist.Tab.firstClear(Tab.java:81) ~[?:?]
    at net.karolek.revoguild.tablist.Tab.<init>(Tab.java:26) ~[?:?]
    at net.karolek.revoguild.manager.types.TabManager.createTab(TabManager.java:53) ~[?:?]
    at net.karolek.revoguild.listeners.LoginListener$1.run(LoginListener.java:26) ~[?:?]
    at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftTask.run(CraftTask.java:53) ~[cb.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at org.bukkit.craftbukkit.v1_7_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:345) [cb.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.v(MinecraftServer.java:600) [cb.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.DedicatedServer.v(DedicatedServer.java:260) [cb.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.u(MinecraftServer.java:558) [cb.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.MinecraftServer.run(MinecraftServer.java:469) [cb.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
    at net.minecraft.server.v1_7_R3.ThreadServerApplication.run(SourceFile:628) [cb.jar:git-Bukkit-1.7.9-R0.1-10-g8688bd4-b3092jnks]
Caused by: java.lang.IllegalArgumentException: Cannot find field with type int
    at net.karolek.revoguild.utils.Reflection.getField(Reflection.java:98) ~[?:?]
    at net.karolek.revoguild.utils.Reflection.getField(Reflection.java:97) ~[?:?]
    at net.karolek.revoguild.utils.Reflection.getField(Reflection.java:97) ~[?:?]
    at net.karolek.revoguild.utils.Reflection.getField(Reflection.java:97) ~[?:?]
    at net.karolek.revoguild.utils.Reflection.getField(Reflection.java:97) ~[?:?]
    at net.karolek.revoguild.utils.Reflection.getField(Reflection.java:48) ~[?:?]
    at net.karolek.revoguild.utils.PacketUtil.<clinit>(PacketUtil.java:31) ~[?:?]
    ... 11 more

**Comment by EastWestFM** [comment]
Tak, wiem. Za 3 minuty będzie update ;)

**Comment by EastWestFM** [comment]
https://github.com/EastWestFM/RevoGuild/releases/tag/v0.2.0-b187
